### ISSUE TITLE
[Mechanics] - Motor mounting hole dimensions

### ISSUE THREAD

**Issue by maidlam** [ut-robotics/picr21-team-sauna-madis#1]
1. Currently, the thrower motor can only be attached with 2 bolts.

![thrower mounting holes](https://user-images.githubusercontent.com/32770145/134387289-16ba42da-9163-4da0-a75f-e90d1a1b9196.png)

The distances between the holes are 16 mm in one axis and 19 mm in the other axis.
**Bolt holes** in [https://hobbyking.com/en_us/ntm-prop-drive-28-26-1000kv-235w.html?___store=en_us](https://hobbyking.com/en_us/ntm-prop-drive-28-26-1000kv-235w.html?___store=en_us)

2. It would be better if the distance to the thrower motor was defined by the center of the motor - changing the current dimension of 9,5 mm causes the center of the motor to move out of place.

**Comment by KasperKaljuste** [comment]
Fixed the dimensions.

**Comment by maidlam** [comment]
The sketch is not fully defined. Set the distances to the blue circles and add an axis through the center of the bigger circle so that the two axis of the holes are perpendicular to each other.
The 18.082 dimension feels weird there.
![Fusion360_2021-09-29_20-07-37](https://user-images.githubusercontent.com/32770145/135329423-472e4ef1-b586-4f96-9a9f-9a6da8990ba6.png)

**Comment by KasperKaljuste** [comment]
Should be solved.

**Comment by Akustav** [comment]
Holes are now OK
