### ISSUE TITLE
Move camera and image processing code to separate files/classes

### ISSUE THREAD

**Issue by ReikoR** [ut-robotics/picr21-team-sauna-madis#16]
Similar camera and image processing code is used in both `cameraImage.py` and `cameraSetThreshold.py` files.

Instead of duplicating the code, it would be better to have separate classes. Those classes could then be used for thresholding and in main robot code.

Some recommendations:
1. Create `class Camera` with `get_rgb_image` method.
2. Create `class ImageProcessing` with `find_objects` method that return balls and baskets. Returned objects could be instances of a [dataclass](https://docs.python.org/3/library/dataclasses.html) that you can define.
3. In main robot code and thresholding create instance of `Camera` and `ImageProcessing`:
```python
camera = Camera()
image_processing = ImageProcessing()

rgb_image = camera.get_rgb_image()
objects = image_processing.find_objects(rgb_image)
```

**Comment by ReikoR** [comment]
Thresholding should also use new camera code so that the camera code is not duplicated.

**Comment by uschults** [comment]
It is using new camera and imageprocess classes.
