### ISSUE TITLE
[Mechanics] - Missing attachement pieces for C-ramps

### ISSUE THREAD

**Issue by maidlam** [ut-robotics/picr21-team-sauna-madis#2]
The C-ramps are currently floating.
![floating c_ramps](https://user-images.githubusercontent.com/32770145/134388110-e10f070e-efa6-4256-a138-2537abdceff5.png)

What are you planning to use to attach these?

**Comment by KasperKaljuste** [comment]
Added spacers to attact C-ramps.

**Comment by maidlam** [comment]
1. The dimensions of the spacers are wrong. The length from side to side is 5,5 mm.
![spacer_dimension](https://user-images.githubusercontent.com/32770145/135328728-b709e60c-d4f1-4f07-8279-e0c2df6d00e2.png)

2. If you are planning to use female-female spacers, then the inside of the spacer needs to be threaded and the holes in the walls should be 3mm in diameter.

**Comment by KasperKaljuste** [comment]
Should be solved now.

**Comment by maidlam** [comment]
Spacers have the wrong dimension. Should be 5,5mm from edge to edge, or 2,75mm from center.
![Fusion360_2021-10-01_21-04-44](https://user-images.githubusercontent.com/32770145/135666870-5096ea65-5bfe-46b3-9298-abb83a0aa4e2.png)

**Comment by KasperKaljuste** [comment]
My bad, fixed it.

**Comment by Akustav** [comment]
Seems fine now.
