### ISSUE TITLE
Avoid using global variables

### ISSUE THREAD

**Issue by ReikoR** [ut-robotics/picr21-team-sauna-madis#26]
https://github.com/ut-robotics/picr21-team-sauna-madis/blob/4c6d1c92842338af8816641a25f335507717bdcf/saun/uusmain.py#L32

Either pass variables as function arguments and return changed variables as function return values or create a class.

**Comment by ReikoR** [comment]
https://github.com/ut-robotics/picr21-team-sauna-madis/blob/13853b7f57bae658ed3a05742286b5a1353aca76/saun/movement.py#L9

https://github.com/ut-robotics/picr21-team-sauna-madis/blob/13853b7f57bae658ed3a05742286b5a1353aca76/saun/movement.py#L31

`move_style` should not be global. It can be class variable.

**Comment by uschults** [comment]
Globals are removed.
