### ISSUE TITLE
[Mechanics] - Inside corner cutouts made weird

### ISSUE THREAD

**Issue by maidlam** [ut-robotics/picr21-team-sauna-madis#3]
The current method - defining the cutout hole center with distances - seems to contain too much manual work.
![cutout hole](https://user-images.githubusercontent.com/32770145/134389430-64859a31-fb65-44c2-81c1-2d518ae6c020.png)

A better method would be make the cutout in the sketch, where the hole for the cutout is coincident with the corner.
[https://digilabor.ut.ee/index.php/Basketball_robot_mechanics_design#Inside_sharp_corners](https://digilabor.ut.ee/index.php/Basketball_robot_mechanics_design#Inside_sharp_corners)

**Comment by KasperKaljuste** [comment]
I used this addin to make the inside corner cutouts: https://github.com/DVE2000/Dogbone

**Comment by maidlam** [comment]
Resolved
