### ISSUE TITLE
Missing NUC power adapter socket cutout

### ISSUE THREAD

**Issue by maidlam** [ut-robotics/picr21-team-sauna-madis#32]
The cutout to attach the NUC power adapter socket is missing.

**Comment by KasperKaljuste** [comment]
Added.

**Comment by Akustav** [comment]
Is the current placement kind of inconvenient when wanting to plug the NUC in? It could be moved forward so the camera does not block it.
![image](https://user-images.githubusercontent.com/5435954/150697741-96fb934f-84fc-4cc6-be44-4867c440db44.png)

**Comment by KasperKaljuste** [comment]
Fixed.
