### ISSUE TITLE
Camera holder could be made more rigid

### ISSUE THREAD

**Issue by maidlam** [ut-robotics/picr21-team-sauna-madis#34]
The camera holder could be made more rigid.

Bolts may not always be strong. When the adjustable camera mount is accidentally moved, the angle change can cause issues with camera settings and distance measurements. Recovering the correct angle is going to require a lot of time as well.

For exmaple, having the mounting plate be attached rigidly (using tenons and bolts), and for the plate to have two exact holes for the camera attachment bolts would help remove those issues.

A crude example of attaching the mounting plate.
![pilt](https://user-images.githubusercontent.com/32770145/150579399-bf626711-5f12-4d92-9577-9d4a1ef176bd.png)

**Comment by KasperKaljuste** [comment]
Changed.
