### ISSUE TITLE
What stops balls going into the chassis?

### ISSUE THREAD

**Issue by maidlam** [ut-robotics/picr21-team-sauna-madis#35]
You should add something around the side to stop balls getting into the chassis.

**Comment by KasperKaljuste** [comment]
Added ribs to the bottom plate. The rear of the robot should be okay as the batteries block the way.

**Comment by maidlam** [comment]
The design should work if the spacers were made taller (using 20mm spacers maybe).
Right now the distance between the rib and top plate is 41,6mm, a ball can get in there.
![Fusion360_2022-01-23_22-43-54](https://user-images.githubusercontent.com/32770145/150697759-91d6822c-3430-4e14-9ce9-8eb6234d1eff.png)

**Comment by KasperKaljuste** [comment]
Fixed.
