### ISSUE TITLE
Top plate blocks some FOV

### ISSUE THREAD

**Issue by maidlam** [ut-robotics/picr21-team-sauna-madis#36]
The camera also has hoirzontal FOV (69 degrees)

The marked parts of the top plate might get in the way of the image, so there should be cutouts in the plate there.
Add a horizontal angle to the FOV to see parts that can get in the way.

![pilt](https://user-images.githubusercontent.com/32770145/150580644-e3f77956-cabf-48be-bc9d-0a2f9577b5f6.png)

**Comment by KasperKaljuste** [comment]
I would like the ball to be seen when it is about to enter the thrower, added cutouts to top plate.
