### ISSUE TITLE
Thrower could be moved inward for better ball centering

### ISSUE THREAD

**Issue by maidlam** [ut-robotics/picr21-team-sauna-madis#37]
The thrower could be moved inward, so the ball has more distance to align itself before hitting the thrower motor.

Currently, the ball can be pulled in from the sides and go through the thrower at an angle.
![pilt](https://user-images.githubusercontent.com/32770145/150583319-f5288a3f-09d7-4d11-8cd3-0c8fc5745996.png)

**Comment by KasperKaljuste** [comment]
Moved it 10mm inward and made the bottom plate guiding angle smaller.
