### ISSUE TITLE
[Mechanics] - Missing bolt holes

### ISSUE THREAD

**Issue by maidlam** [ut-robotics/picr21-team-sauna-madis#4]
There are a few missing bolt holes in one of the walls.
![Fusion360_2021-09-22_19-34-28](https://user-images.githubusercontent.com/32770145/134398565-d39ab997-8b76-492e-ba23-3a4bb43d647a.png)

![Fusion360_2021-09-22_21-13-04](https://user-images.githubusercontent.com/32770145/134398794-206081cf-efe3-49dd-8943-d263724dc7bb.png)

**Comment by KasperKaljuste** [comment]
Added missing bolt holes.

**Comment by maidlam** [comment]
Resolved
