### ISSUE TITLE
Why balls are sorted based on x location

### ISSUE THREAD

**Issue by Akustav** [ut-robotics/picr21-team-sauna-madis#41]
https://github.com/ut-robotics/picr21-team-sauna-madis/blob/a80c9164e964e816dcf8a4658698719917ffa470/saun/imageProcess.py#L109

Why are balls sorted by their x coordinate, when y can be used to estimate the proximity of balls?

EDIT:
The variable naming here is horrible. Change it for readability

**Comment by uschults** [comment]
it is sorted by Y coordinates the x is ball coordinates, and x[1] takes the y coordinate

**Comment by Akustav** [comment]
Inside the context of coordinates, using x as the lambda variable is very unfortunate and at times confusing

**Comment by uschults** [comment]
i will change it for better readablity
