### ISSUE TITLE
Inconsistent variable naming

### ISSUE THREAD

**Issue by Akustav** [ut-robotics/picr21-team-sauna-madis#43]
https://github.com/ut-robotics/picr21-team-sauna-madis/blob/a80c9164e964e816dcf8a4658698719917ffa470/saun/imageProcess.py#L62-L65

You should unify code to use either camelCase or snake_case, not mixing them here-and-there.

Technically the best would be to use PEP 8: https://www.python.org/dev/peps/pep-0008/

**Comment by uschults** [comment]
Changed all variable to snake_case
