### ISSUE TITLE
Resolution data should be held in Image

### ISSUE THREAD

**Issue by Akustav** [ut-robotics/picr21-team-sauna-madis#44]
Currently the frame center point is held inside main.py while the resolution is inside image.py. You should unify where resolution data is kept and since it is more connected to the Image, it should be inside image.py, not main.py.

https://github.com/ut-robotics/picr21-team-sauna-madis/blob/a80c9164e964e816dcf8a4658698719917ffa470/saun/main.py#L15

**Comment by uschults** [comment]
it is needed for game logic, not for image or image processing.

**Comment by Akustav** [comment]
Then why not hold frame resolution inside Image and calculate camera_x_mid as follows` camera_x_mid = image.x_resolution / 2`

**Comment by uschults** [comment]
yes, done
