### ISSUE TITLE
Remove functionality duplication

### ISSUE THREAD

**Issue by Akustav** [ut-robotics/picr21-team-sauna-madis#45]
https://github.com/ut-robotics/picr21-team-sauna-madis/blob/4fb64b509e46eff53c771e944f97920e92c6cfa2/saun/main.py#L50-L64

get_ballNbasket_cord() should use get_ball_cord() and get_basket_cord() to avoid code duplication. Additionally, the sub-functions should take frame data as input to avoid fetching new frame data upon call.

**Comment by Akustav** [comment]
More code duplication:

https://github.com/ut-robotics/picr21-team-sauna-madis/blob/4fb64b509e46eff53c771e944f97920e92c6cfa2/saun/main.py#L70-L80

**Comment by Akustav** [comment]
Additionally, `def move_style_check(move_style):` is a very ambiguous name. What does it check?

**Comment by uschults** [comment]
getting coordinates now takes frame data and removed duplication.
