### ISSUE TITLE
Question with if-else

### ISSUE THREAD

**Issue by Akustav** [ut-robotics/picr21-team-sauna-madis#47]
https://github.com/ut-robotics/picr21-team-sauna-madis/blob/4fb64b509e46eff53c771e944f97920e92c6cfa2/saun/main.py#L152-L161

In this logic, what happens when basket_depth is smaller than 0.5? It continues the loop?

**Comment by uschults** [comment]
right now, it'll continue the loop, as the find another ball is not implemented. Our focus right now is to be able to only complete the first programming tasks.
