### ISSUE TITLE
[Mechanics] - Add robot chassis to assembly

### ISSUE THREAD

**Issue by maidlam** [ut-robotics/picr21-team-sauna-madis#5]
Adding the robot chassis to the assembly can give a better visual, if the components are physically mountable to the robot, and help gauge the distance between the thrower motor and the ground.

**Comment by KasperKaljuste** [comment]
Added the bottom part of the chassis to thrower. Are other parts necessary?

**Comment by maidlam** [comment]
1. Ideally, the height of the bottom plate should be set as it is in real life. Then you can then check how high the thrower motor is from the floor (to see if a ball will touch the motor). You could have the XY plane act as the floor in the model.

2. You should add motors and motor mounts. I think the thrower walls might not interfere with the motors, but good to check.
![thrower_motors_positions](https://user-images.githubusercontent.com/32770145/135327921-594f7b25-9c01-4301-a513-00ef7640d6c3.png)

3. Add a rectangle to the thrower motor to visualize the wires coming from it (something like picture below). Verify the angle on your actual motor.
![thrower_motor_wires](https://user-images.githubusercontent.com/32770145/135328196-4857ddc4-3fd3-45d4-9ae9-bb5ec1886fa5.png)

**Comment by KasperKaljuste** [comment]
Added motor mount, motor, visualized wires.

**Comment by Akustav** [comment]
Hey! Seems like the motor sits too low now. Comparison with ball in picture:
![image](https://user-images.githubusercontent.com/5435954/135716866-e85d3393-66b4-40d0-be8c-7c273de73e39.png)

**Comment by KasperKaljuste** [comment]
The motors edge is now 35mm from the ground.

**Comment by KasperKaljuste** [comment]
Raised the motor to 53mm.
