### ISSUE TITLE
[Mechanics] - internal ramp radius too small

### ISSUE THREAD

**Issue by Akustav** [ut-robotics/picr21-team-sauna-madis#6]
I think the space for the ball between the ramp and motor is too small. It should compress the ball in the range of 5-10 mm. This is too much:
![image](https://user-images.githubusercontent.com/5435954/135716903-d354cb53-c811-4bf4-ba42-07713169607f.png)

**Comment by KasperKaljuste** [comment]
Made the radius 35mm

**Comment by Akustav** [comment]
Seems OK.
